// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.PowerUp.subsystems;

import org.usfirst.frc5506.PowerUp.Robot;
import org.usfirst.frc5506.PowerUp.RobotMap;
import org.usfirst.frc5506.PowerUp.commands.TeleopDrive;
//import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveBase extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
	private static final double TOP_SPEED = 0.75;
	private double accelerationZone = 0.25;
    private double direction;
    private double correction;
    private double difference;
    private final static PowerDistributionPanel pdp = RobotMap.pdp;
	private final Encoder leftRevs = RobotMap.leftRevs;
    private final Encoder rightRevs = RobotMap.rightRevs;
    private final DifferentialDrive drive = RobotMap.drive;
    
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	setDefaultCommand(new TeleopDrive());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void drive(double forwardLeft, double turnRight) {
        //deadband
        if(Math.abs(forwardLeft) < .10)
        forwardLeft = 0;
        
        if(Math.abs(turnRight)<.10)
        	turnRight = 0;
        
        if(Robot.driveMode)//if arcadeDrive is selected on smartdash
        drive.arcadeDrive(forwardLeft, turnRight);//arcade drive
        
        else {//if tank drive selected
        	drive.tankDrive(forwardLeft, turnRight);//tank drive
        }
    }
    
    public Encoder getLeftRotation() {
    	return leftRevs;
    }
    
    public Encoder getRightRotation() {
    	return rightRevs;
    }
    
    public void resetEncoders() {
    	leftRevs.reset();
    	rightRevs.reset();
    }

    public void driveLinear(boolean forwards) {
    	if(forwards)
    		direction = -0.5;
    	else
    		direction = 0.5;
    	
    	difference = rightRevs.getDistance()-leftRevs.getDistance();//difference of distances
    																//wheels travelled
    	
    	if(Math.abs(difference)>3)//if one side has gone farther than another
    		correction = difference;//turn the robot the amount that it's off
    	else
    		correction = 0;
    	
    	drive.arcadeDrive(direction, (correction/20));//play with this number -- imprecise
    								//if it gets off by more than half an inch, turn at 5%
    }
    
    public void stop() {
    	drive.stopMotor();//stop DifferentialDrive object
    }
    
    public DifferentialDrive getMotors() {
    	return drive;
    }
    
    /**
     * This takes in how far through your drive command you are, and returns what percentage your motors
     * should run at so that you have a smooth acceleration and deceleration curve.
     * 
     * @param percentDone
     * @return The percentage the motors should run at through a drive function
     */
    public double driveCurve(double percentDone) {
    	if(percentDone<accelerationZone)//if were supposed to be accelerating up
    		return (TOP_SPEED*percentDone*percentDone) / ( accelerationZone * accelerationZone );//return value of formula for first 25%
    	else if(percentDone>(1-accelerationZone))//if were supposed to be slowing down (distance of accelerationZone, but moving backwards from 1, not forwards from 0
    		return TOP_SPEED*(percentDone-1)*(percentDone-1) / (accelerationZone * accelerationZone);//return value of formula FLIPPED ACROSS Y AXIS, so that we are deceleration, not accelerating a lot
    	else
    		return TOP_SPEED;//if not ac/de celerating, we gotta go fast
    }
    
    public void showPDPStats() {
    	double[] pdpStats = new double[6];
	
    	pdpStats[0] = pdp.getTotalCurrent();
    	pdpStats[1] = pdp.getCurrent(0);
    	pdpStats[2] = pdp.getCurrent(1);
    	pdpStats[3] = pdp.getCurrent(2);
    	pdpStats[4] = pdp.getCurrent(3);
    	pdpStats[5] = pdp.getCurrent(7);

	
    	SmartDashboard.putNumberArray("PDP Stats", pdpStats);
    }
}