// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.PowerUp.subsystems;

import org.usfirst.frc5506.PowerUp.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DoubleSolenoid;

/**
 *
 */
public class Hand extends Subsystem {
	
    private final DoubleSolenoid gripper = RobotMap.handgripper;

    @Override
    public void initDefaultCommand() {
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    //Same basic pneumatic commands as Arm
    public void grip() {
    	gripper.set(DoubleSolenoid.Value.kReverse);
    }
    
    public void ungrip() {
    	gripper.set(DoubleSolenoid.Value.kForward);
    }
    
    public void stop() {
    	gripper.set(DoubleSolenoid.Value.kOff);
    }

}

