// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.PowerUp.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc5506.PowerUp.*;

/**
 * In a command group, you can run many sequenced commands. To do so, use addSequential(Command command) methods or
 * addParallel(Command command). An addParallel will run at the same time as the command beneath it.
 **/
public class AutoTwo extends CommandGroup {
	
	private double waitTime;
	private char endPosition;
	
	public AutoTwo() {
		this.endPosition = Robot.endPosition;
		this.waitTime = Robot.waitTime;
		
		addSequential(new Wait(waitTime));
		
		String gameData = Robot.gameData;
		if(gameData!=null) {//if gameData exists, do the command, if not then just sit there
			switch(endPosition) {
			/*case 'a'://L==R for a
				addSequential(new DriveLinear(4));
				addSequential(new Turn(90));
				addSequential(new DriveLinear(72));
				addSequential(new Turn(-45));
				addSequential(new DriveLinear(47.376154));
				addSequential(new Turn(-45));
				addSequential(new DriveLinear(84.75));
				break;*/
				
			case 'b':
				
				/*//addSequential(new AutoTwo('a', "Hi"));
				addSequential(new DriveLinear(4));
				addSequential(new Turn(90));
				addSequential(new DriveLinear(72));
				addSequential(new Turn(-45));
				addSequential(new DriveLinear(47.376154));
				addSequential(new Turn(-45));
				addSequential(new DriveLinear(84.75));
				//end AutoTwo(a)
				
				if(gameData.charAt(0)=='R') {
				//	addSequential(new AutoThree('b', "R"));
					addSequential(new DriveLinear(85));
					addSequential(new Turn(-90));
					addParallel(new Curl(30));
					addSequential(new DriveLinear(45));
					addSequential(new MoveHand(true));
					//end AutoThree('b', "R")
				} else {
				//	addSequential(new AutoThree('b', "L"));
					addSequential(new DriveLinear(153.75));
					addSequential(new Turn(-90));
					addSequential(new DriveLinear(284));
					addSequential(new Turn(-90));
					addSequential(new DriveLinear(68.75));
					addSequential(new Turn(-90));
					addParallel(new Curl(30));
					addSequential(new DriveLinear(45));
					//Same time as above command, run the command below
					addSequential(new MoveHand(true));
					//end AutoThree('b', "L")
				}*/
			}
		}
	}
}
