// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.PowerUp.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *    There's actually no special methods or robotbuilder stuff for CommandGroup,
 *    You just add in a bunch of addSequential()s and addParallel()s for your routine
 *    until the routine is finished. Nice, right? -DM
 **/
public class AutoThree extends CommandGroup {
	
	public AutoThree(char letter, String gameData) {
		switch(letter) {
		case 'a'://L == R for a
			addSequential(new DriveAuto(4));
			addSequential(new Turn(45));
			addSequential(new DriveAuto(51.265242));
			addSequential(new Turn(-45));
			addSequential(new DriveAuto(83.75));
		}
	}
}
