// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.PowerUp.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5506.PowerUp.Robot;

/**
 *
 */
public class MoveArm extends Command {

    private boolean isExtending;

    public MoveArm(boolean isExtending) {
        requires(Robot.arm);
        
        this.isExtending = isExtending;
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	//Robot.armMoving = true;
    //	System.out.println("Move Arm initialize: "+Robot.armMoving);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if(isExtending) {
    		Robot.arm.extend();
    	} else {
    		Robot.arm.retract();
    	}
    	setTimeout(0.1);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	//System.out.println(Robot.armMoving);//always printing false
    	//return !(Robot.armMoving);
    	//System.out.println(isTimedOut());
    	return isTimedOut();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.arm.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	//Robot.arm.stop();//stop first command when the second command 
    					 //comes in with moving=false
    }
}
