// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.PowerUp;

import edu.wpi.first.wpilibj.CounterBase.EncodingType;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
//import edu.wpi.first.wpilibj.AnalogGyro;
//import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DoubleSolenoid armextendor;
    public static DoubleSolenoid handgripper;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Encoder leftRevs;
    public static Encoder rightRevs;
    public static Encoder armPos;
    //public static Gyro gyro;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	
    	armextendor = new DoubleSolenoid(0, 6, 7);
        LiveWindow.addActuator("Arm", "extendor", armextendor);
        
        handgripper = new DoubleSolenoid(0, 4, 5);
        LiveWindow.addActuator("Hand", "gripper", handgripper);
        //these lines were generated by Robotbuilder, had to change port numbers so I moved it out -DM
        
        //these are all made by me because I couldn't get RobotBuilder to export for some reason?
        armPos = new Encoder(2, 4, false, EncodingType.k4X);
        leftRevs = new Encoder(0, 3, false, EncodingType.k4X);
        rightRevs = new Encoder(1, 5, false, EncodingType.k4X);
        
        LiveWindow.addSensor("Arm", "Position", armPos);
        //http://www.andymark.com/E4T-OEM-Miniature-Optical-Encoder-Kit-p/am-3132.htm
        //According to the link, 1440 pulses per revolution, so one encoder distance is one wheel rotation.
        armPos.setDistancePerPulse((6*Math.PI)/1440);//1440 rev per pulse ; 6pi inches per rev
        //armPos.setPIDSourceParameter(PIDSourceParameter.kRate);//I guess we need an import, don't know it thoug
    }
}
